name: CI
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: df -m
    - run: du -sm $ANDROID_HOME/*
    - run: du -sm /usr/local/lib/* /usr/local/share/* /opt/*


